apimServiceName: apiopsprdapimlab
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: prod
apis:
  - name: colors-api
    properties:
      serviceUrl: http://colors-api-prd.azurelaboratory.com